/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stoppetBehandling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "saksnummer": "4LFL5CW",
                     *       "sakStatus": "LØPENDE",
                     *       "behandlingReferanse": "bba4cccb-b91d-41be-940f-5cffa46fe62b",
                     *       "relatertBehandling": null,
                     *       "behandlingOpprettetTidspunkt": "2025-02-06T08:40:54.459463285",
                     *       "mottattTid": "2025-02-05T08:40:54.45949276",
                     *       "behandlingStatus": "OPPRETTET",
                     *       "behandlingType": "Førstegangsbehandling",
                     *       "soknadsFormat": "DIGITAL",
                     *       "ident": "1403199012345",
                     *       "versjon": "b21e88bca4533d3e0ee3a15f51a87cbaa11a7e9c",
                     *       "årsakTilBehandling": [
                     *         "SØKNAD"
                     *       ],
                     *       "avklaringsbehov": [
                     *         {
                     *           "avklaringsbehovDefinisjon": {
                     *             "kode": "5001",
                     *             "type": "MANUELT_PÅKREVD",
                     *             "løsesISteg": "AVKLAR_STUDENT",
                     *             "kreverToTrinn": true,
                     *             "kvalitetssikres": false,
                     *             "løsesAv": [
                     *               "SAKSBEHANDLER_NASJONAL"
                     *             ]
                     *           },
                     *           "status": "AVSLUTTET",
                     *           "endringer": [
                     *             {
                     *               "status": "OPPRETTET",
                     *               "tidsstempel": "2025-02-06T08:30:54.45884972",
                     *               "frist": null,
                     *               "endretAv": "Kelvin",
                     *               "årsakTilSattPåVent": null,
                     *               "årsakTilRetur": []
                     *             },
                     *             {
                     *               "status": "AVSLUTTET",
                     *               "tidsstempel": "2025-02-06T08:35:54.458915793",
                     *               "frist": null,
                     *               "endretAv": "Z994573",
                     *               "årsakTilSattPåVent": null,
                     *               "årsakTilRetur": []
                     *             }
                     *           ]
                     *         },
                     *         {
                     *           "avklaringsbehovDefinisjon": {
                     *             "kode": "5003",
                     *             "type": "MANUELT_PÅKREVD",
                     *             "løsesISteg": "AVKLAR_SYKDOM",
                     *             "kreverToTrinn": true,
                     *             "kvalitetssikres": true,
                     *             "løsesAv": [
                     *               "SAKSBEHANDLER_OPPFOLGING"
                     *             ]
                     *           },
                     *           "status": "OPPRETTET",
                     *           "endringer": [
                     *             {
                     *               "status": "OPPRETTET",
                     *               "tidsstempel": "2025-02-06T08:37:54.458945147",
                     *               "frist": null,
                     *               "endretAv": "Kelvin",
                     *               "årsakTilSattPåVent": null,
                     *               "årsakTilRetur": []
                     *             }
                     *           ]
                     *         }
                     *       ],
                     *       "hendelsesTidspunkt": "2025-02-06T08:40:54.459762504",
                     *       "avsluttetBehandling": null,
                     *       "identerForSak": []
                     *     } */
                    "application/json": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.StoppetBehandling"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OppgaveHendelse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.oppgave.statistikk.OppgaveHendelse"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postmottak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DokumentflytStoppetHendelse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlingstid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** For en gitt dag, hva er gjennomsnittlig alder på alle behandlinger som ble avsluttet på denne dagen. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlingstidPerDagDTO`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlingstid/lukkede-siste-dager/{antallDager}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Henter alle behandlinger som er lukket i de siste n dager, og regner ut snittalderen på disse. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path: {
                    /** @description Antall dager å regne på */
                    antallDager: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/\u00E5pne-behandlinger-per-behandlingstype": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antall åpne behandlinger og gjennomsnittsalder på dem per behandlingstype. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$Antall\u00C5pneOgTypeOgGjennomsnittsalder`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandling-per-avklaringsbehov": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antall åpne behandlinger per avklaringsbehov. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingPerAvklaringsbehov"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandling-per-steggruppe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingPerSteggruppe"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/fordeling-\u00E5pne-behandlinger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returnerer en liste over fordelingen på åpne behandlinger. Bøtte nr 1 teller antall
         *     behandlinger som er enhet * bøtteStørrelse gammel . Bøtte nr antallBøtter + 1 teller
         *     antall behandlinger eldre enn bøttestørrelsen. */
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange bøtter skal åpne behandlinger plasseres i? */
                    "antallB\u00F8tter"?: number;
                    /** @description Week, month, day, etc. */
                    enhet: "DAG" | "UKE" | "MÅNED" | "ÅR";
                    /** @description Hver bøtte er enhet * bøtteStørrelse stor. */
                    "b\u00F8tteSt\u00F8rrelse"?: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.Fordeling\u00C5pneBehandlinger"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/fordeling-lukkede-behandlinger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returnerer en liste over behandlingstiden på lukkede behandlinger. Bøtte nr 1 teller antall
         *     behandlinger som er enhet * bøtteStørrelse gammel . Bøtte nr antallBøtter + 1 teller
         *     antall behandlinger eldre enn bøttestørrelsen. */
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange bøtter skal åpne behandlinger plasseres i? */
                    "antallB\u00F8tter"?: number;
                    /** @description Week, month, day, etc. */
                    enhet: "DAG" | "UKE" | "MÅNED" | "ÅR";
                    /** @description Hver bøtte er enhet * bøtteStørrelse stor. */
                    "b\u00F8tteSt\u00F8rrelse"?: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.FordelingLukkedeBehandlinger"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/utvikling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange dager å lage fordeling på. */
                    antallDager: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlinEndringerPerDag`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/p\u00E5-vent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.Vente\u00E5rsakOgGjennomsnitt"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/\u00E5rsak-til-behandling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: ("Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring")[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingAarsakAntallGjennomsnitt"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon": {
            /** @enum {string} */
            kode: "9001" | "9002" | "9003" | "5001" | "5003" | "5004" | "5005" | "5006" | "5007" | "5008" | "5009" | "5010" | "5011" | "5012" | "5013" | "5014" | "5015" | "5016" | "5017" | "5018" | "5097" | "5098" | "5099" | "5050";
            kreverToTrinn: boolean;
            kvalitetssikres: boolean;
            "l\u00F8sesAv": ("SAKSBEHANDLER_OPPFOLGING" | "SAKSBEHANDLER_NASJONAL" | "KVALITETSSIKRER" | "BESLUTTER" | "LES" | "PRODUKSJONSSTYRING" | "DRIFT")[];
            /** @enum {string} */
            "l\u00F8sesISteg": "START_BEHANDLING" | "VURDER_ALDER" | "VURDER_LOVVALG" | "VURDER_MEDLEMSKAP" | "AVKLAR_STUDENT" | "VURDER_BISTANDSBEHOV" | "VURDER_SYKEPENGEERSTATNING" | "FASTSETT_SYKDOMSVILKÅRET" | "VURDER_YRKESSKADE" | "FRITAK_MELDEPLIKT" | "KVALITETSSIKRING" | "BARNETILLEGG" | "AVKLAR_SYKDOM" | "FASTSETT_ARBEIDSEVNE" | "FASTSETT_BEREGNINGSTIDSPUNKT" | "FASTSETT_GRUNNLAG" | "VIS_GRUNNLAG" | "FASTSETT_UTTAK" | "SAMORDNING_GRADERING" | "EFFEKTUER_11_7" | "DU_ER_ET_ANNET_STED" | "BEREGN_TILKJENT_YTELSE" | "SIMULERING" | "FORESLÅ_VEDTAK" | "FATTE_VEDTAK" | "BREV" | "IVERKSETT_VEDTAK" | "UDEFINERT";
            /** @enum {string} */
            type: "MANUELT_PÅKREVD" | "MANUELT_FRIVILLIG" | "BREV" | "BREV_VENTEPUNKT" | "VENTEPUNKT";
            name: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto": {
            avklaringsbehovDefinisjon: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon"];
            endringer: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO"][];
            /** @enum {string} */
            status: "OPPRETTET" | "AVSLUTTET" | "TOTRINNS_VURDERT" | "SENDT_TILBAKE_FRA_BESLUTTER" | "KVALITETSSIKRET" | "SENDT_TILBAKE_FRA_KVALITETSSIKRER" | "AVBRUTT";
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO": {
            endretAv: string;
            /**
             * Format: date
             * @example 2025-02-06
             */
            frist?: string | null;
            /** @enum {string} */
            status: "OPPRETTET" | "AVSLUTTET" | "TOTRINNS_VURDERT" | "SENDT_TILBAKE_FRA_BESLUTTER" | "KVALITETSSIKRET" | "SENDT_TILBAKE_FRA_KVALITETSSIKRER" | "AVBRUTT";
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            tidsstempel: string;
            "\u00E5rsakTilRetur": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur"][];
            /** @enum {string|null} */
            "\u00E5rsakTilSattP\u00E5Vent"?: "VENTER_PÅ_OPPLYSNINGER" | "VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER" | "VENTER_PÅ_MEDISINSKE_OPPLYSNINGER" | "VENTER_PÅ_VURDERING_AV_ROL" | "VENTER_PÅ_SVAR_FRA_BRUKER" | "VENTER_PÅ_MASKINELL_AVKLARING" | null;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur": {
            /** @enum {string} */
            "\u00E5rsak": "MANGELFULL_BEGRUNNELSE" | "MANGLENDE_UTREDNING" | "FEIL_LOVANVENDELSE" | "ANNET";
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.AvsluttetBehandlingDTO": {
            beregningsGrunnlag?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO"];
            diagnoser?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Diagnoser"];
            tilkjentYtelse: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelseDTO"];
            "vilk\u00E5rsResultat": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsResultatDTO"];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO": {
            grunnlag11_19dto?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            "grunnlagUf\u00F8re"?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagUf\u00F8reDTO"];
            grunnlagYrkesskade?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagYrkesskadeDTO"];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Diagnoser": {
            bidiagnoser: string[];
            diagnosekode: string;
            kodeverk: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO": {
            er6GBegrenset: boolean;
            erGjennomsnitt: boolean;
            /** Format: double */
            grunnlaget: number;
            /** @description Key type: kotlin.String */
            inntekter: {
                [key: string]: number;
            };
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagUf\u00F8reDTO": {
            grunnlag: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            grunnlagYtterligereNedsatt: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            grunnlaget: number;
            /** @enum {string} */
            type: "STANDARD" | "YTTERLIGERE_NEDSATT";
            /** @description Key type: kotlin.String */
            "uf\u00F8reInntekterFraForeg\u00E5ende\u00C5r": {
                [key: string]: number;
            };
            /** Format: int32 */
            "uf\u00F8reYtterligereNedsattArbeidsevne\u00C5r": number;
            /** Format: int32 */
            "uf\u00F8regrad": number;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagYrkesskadeDTO": {
            andelSomIkkeSkyldesYrkesskade: number;
            andelSomSkyldesYrkesskade: number;
            /** Format: int32 */
            andelYrkesskade: number;
            "antatt\u00C5rligInntektYrkesskadeTidspunktet": number;
            /** Format: int32 */
            benyttetAndelForYrkesskade: number;
            beregningsgrunnlag: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO"];
            grunnlagEtterYrkesskadeFordel: number;
            grunnlagForBeregningAvYrkesskadeandel: number;
            grunnlaget: number;
            "inkludererUf\u00F8re": boolean;
            /** Format: int32 */
            terskelverdiForYrkesskade: number;
            /** Format: int32 */
            yrkesskadeTidspunkt: number;
            yrkesskadeinntektIG: number;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.StoppetBehandling": {
            avklaringsbehov: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto"][];
            avsluttetBehandling?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.AvsluttetBehandlingDTO"];
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            behandlingOpprettetTidspunkt: string;
            /** Format: uuid */
            behandlingReferanse: string;
            /** @enum {string} */
            behandlingStatus: "OPPRETTET" | "UTREDES" | "IVERKSETTES" | "AVSLUTTET";
            /** @enum {string} */
            behandlingType: "Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage";
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            hendelsesTidspunkt: string;
            ident: string;
            identerForSak: string[];
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            mottattTid: string;
            /** Format: uuid */
            relatertBehandling?: string | null;
            /** @enum {string} */
            sakStatus: "OPPRETTET" | "UTREDES" | "LØPENDE" | "AVSLUTTET";
            saksnummer: string;
            /** @enum {string} */
            soknadsFormat: "DIGITAL" | "PAPIR";
            versjon: string;
            "\u00E5rsakTilBehandling": ("SØKNAD" | "AKTIVITETSMELDING" | "MELDEKORT" | "LEGEERKLÆRING" | "AVVIST_LEGEERKLÆRING" | "DIALOGMELDING" | "G_REGULERING" | "REVURDER_MEDLEMSKAP" | "REVURDER_YRKESSKADE" | "REVURDER_BEREGNING")[];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelseDTO": {
            perioder: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelsePeriodeDTO"][];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelsePeriodeDTO": {
            /** Format: double */
            dagsats: number;
            /**
             * Format: date
             * @example 2025-02-06
             */
            fraDato: string;
            /** Format: double */
            gradering: number;
            /**
             * Format: date
             * @example 2025-02-06
             */
            tilDato: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rDTO": {
            perioder: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsPeriodeDTO"][];
            /** @enum {string} */
            "vilk\u00E5rType": "ALDERSVILKÅRET" | "SYKDOMSVILKÅRET" | "BISTANDSVILKÅRET" | "MEDLEMSKAP" | "GRUNNLAGET" | "SYKEPENGEERSTATNING";
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsPeriodeDTO": {
            "avslags\u00E5rsak"?: string | null;
            /**
             * Format: date
             * @example 2025-02-06
             */
            fraDato: string;
            "innvilgelses\u00E5rsak"?: string | null;
            manuellVurdering: boolean;
            /**
             * Format: date
             * @example 2025-02-06
             */
            tilDato: string;
            /** @enum {string} */
            utfall: "IKKE_VURDERT" | "IKKE_RELEVANT" | "OPPFYLT" | "IKKE_OPPFYLT";
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsResultatDTO": {
            /** @enum {string} */
            typeBehandling: "Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage";
            "vilk\u00E5r": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rDTO"][];
        };
        "no.nav.aap.oppgave.OppgaveDto": {
            avklaringsbehovKode: string;
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            behandlingOpprettet: string;
            /** Format: uuid */
            behandlingRef?: string | null;
            /** @enum {string} */
            behandlingstype: "FØRSTEGANGSBEHANDLING" | "REVURDERING" | "TILBAKEKREVING" | "KLAGE" | "DOKUMENT_HÅNDTERING" | "JOURNALFØRING";
            endretAv?: string | null;
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            endretTidspunkt?: string | null;
            enhet: string;
            /** Format: int64 */
            id?: number | null;
            /** Format: int64 */
            journalpostId?: number | null;
            "oppf\u00F8lgingsenhet"?: string | null;
            opprettetAv: string;
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            opprettetTidspunkt: string;
            personIdent?: string | null;
            personNavn?: string | null;
            /**
             * Format: date
             * @example 2025-02-06
             */
            "p\u00E5VentTil"?: string | null;
            "p\u00E5Vent\u00C5rsak"?: string | null;
            reservertAv?: string | null;
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            reservertTidspunkt?: string | null;
            saksnummer?: string | null;
            /** @enum {string} */
            status: "OPPRETTET" | "AVSLUTTET";
            /** Format: int64 */
            versjon: number;
        };
        "no.nav.aap.oppgave.statistikk.OppgaveHendelse": {
            /** @enum {string} */
            hendelse: "OPPRETTET" | "GJENÅPNET" | "OPPDATERT" | "RESERVERT" | "AVRESERVERT" | "LUKKET";
            oppgaveDto: components["schemas"]["no.nav.aap.oppgave.OppgaveDto"];
        };
        "no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon": {
            /** @enum {string} */
            kode: "9001" | "1337" | "1338" | "1339" | "1340" | "1341";
            kreverToTrinn: boolean;
            "l\u00F8sesAv": ("SAKSBEHANDLER_OPPFOLGING" | "SAKSBEHANDLER_NASJONAL" | "KVALITETSSIKRER" | "BESLUTTER" | "LES" | "PRODUKSJONSSTYRING" | "DRIFT")[];
            /** @enum {string} */
            "l\u00F8sesISteg": "DIGITALISER_DOKUMENT" | "START_BEHANDLING" | "AVKLAR_TEMA" | "SETT_FAGSAK" | "ENDELIG_JOURNALFØRING" | "OVERLEVER_TIL_FAGSYSTEM" | "UDEFINERT" | "AVKLAR_SAK" | "VIDERESEND" | "IVERKSETTES";
            /** @enum {string} */
            type: "MANUELT_PÅKREVD" | "MANUELT_FRIVILLIG" | "VENTEPUNKT";
            name: string;
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto": {
            avklaringsbehovDefinisjon: components["schemas"]["no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon"];
            definisjon: components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.DefinisjonDTO"];
            endringer: components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO"][];
            /** @enum {string} */
            status: "OPPRETTET" | "AVSLUTTET" | "SENDT_TILBAKE_FRA_BESLUTTER" | "SENDT_TILBAKE_FRA_KVALITETSSIKRER" | "AVBRUTT";
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.DefinisjonDTO": {
            /** @enum {string} */
            behovType: "MANUELT_PÅKREVD" | "MANUELT_FRIVILLIG" | "VENTEPUNKT";
            /** @enum {string} */
            "l\u00F8sesISteg": "DIGITALISER_DOKUMENT" | "START_BEHANDLING" | "AVKLAR_TEMA" | "SETT_FAGSAK" | "ENDELIG_JOURNALFØRING" | "OVERLEVER_TIL_FAGSYSTEM" | "UDEFINERT" | "AVKLAR_SAK" | "VIDERESEND" | "IVERKSETTES";
            /** @enum {string} */
            type: "9001" | "1337" | "1338" | "1339" | "1340" | "1341";
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse": {
            avklaringsbehov: components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto"][];
            /** @enum {string} */
            behandlingType: "DokumentHåndtering" | "Journalføring";
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            hendelsesTidspunkt: string;
            ident: string;
            journalpostId: components["schemas"]["no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId"];
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            opprettetTidspunkt: string;
            /** Format: uuid */
            referanse: string;
            saksnummer?: string | null;
            /** @enum {string} */
            status: "OPPRETTET" | "UTREDES" | "IVERKSETTES" | "AVSLUTTET";
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO": {
            endretAv: string;
            /**
             * Format: date
             * @example 2025-02-06
             */
            frist?: string | null;
            /** @enum {string} */
            status: "OPPRETTET" | "AVSLUTTET" | "SENDT_TILBAKE_FRA_BESLUTTER" | "SENDT_TILBAKE_FRA_KVALITETSSIKRER" | "AVBRUTT";
            /**
             * Format: date-time
             * @example 2025-02-06T08:40:54.40592374
             */
            tidsstempel: string;
        };
        "no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId": {
            /** Format: int64 */
            referanse: number;
        };
        "no.nav.aap.statistikk.api.FordelingLukkedeBehandlinger": {
            /** Format: int32 */
            antall: number;
            /** Format: int32 */
            "b\u00F8tte": number;
        };
        "no.nav.aap.statistikk.api.Fordeling\u00C5pneBehandlinger": {
            /** Format: int32 */
            antall: number;
            /** Format: int32 */
            "b\u00F8tte": number;
        };
        "no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$Antall\u00C5pneOgTypeOgGjennomsnittsalder`": {
            /** Format: int32 */
            "antall\u00C5pne": number;
            /** @enum {string} */
            behandlingstype: "Førstegangsbehandling" | "Revurdering" | "Tilbakekreving" | "Klage" | "Dokumenthåndtering" | "Journalføring";
            /** Format: double */
            gjennomsnittsalder: number;
        };
        "no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlinEndringerPerDag`": {
            /** Format: int32 */
            avsluttede: number;
            /**
             * Format: date
             * @example 2025-02-06
             */
            dato: string;
            /** Format: int32 */
            nye: number;
            /** Format: int32 */
            totalt: number;
        };
        "no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlingstidPerDagDTO`": {
            /**
             * Format: date
             * @example 2025-02-06
             */
            dag: string;
            /** Format: double */
            snitt: number;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingAarsakAntallGjennomsnitt": {
            /** Format: int32 */
            antall: number;
            /** Format: double */
            gjennomsnittligAlder: number;
            "\u00E5rsak": string;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingPerAvklaringsbehov": {
            /** Format: int32 */
            antall: number;
            /** @description Avklaringsbehovkoden. */
            behov: string;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingPerSteggruppe": {
            /** Format: int32 */
            antall: number;
            /** @enum {string} */
            steggruppe: "START_BEHANDLING" | "ALDER" | "LOVVALG" | "MEDLEMSKAP" | "BARNETILLEGG" | "STUDENT" | "SYKDOM" | "GRUNNLAG" | "ET_ANNET_STED" | "UNDERVEIS" | "TILKJENT_YTELSE" | "SIMULERING" | "VEDTAK" | "FATTE_VEDTAK" | "KVALITETSSIKRING" | "IVERKSETT_VEDTAK" | "BREV" | "UDEFINERT";
        };
        "no.nav.aap.statistikk.produksjonsstyring.Vente\u00E5rsakOgGjennomsnitt": {
            /** Format: int32 */
            antall: number;
            /** Format: double */
            gjennomsnittligAlder: number;
            "\u00E5rsak": string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
