/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stoppetBehandling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.StoppetBehandling"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppdatertBehandling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.StoppetBehandling"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OppgaveHendelse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.oppgave.statistikk.OppgaveHendelse"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postmottak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DokumentflytStoppetHendelse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlingstid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** For en gitt dag, hva er gjennomsnittlig alder på alle behandlinger som ble avsluttet på denne dagen. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingstidGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.BehandlingstidPerDagDTO"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/\u00E5pne-behandlinger-per-behandlingstype": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antall åpne behandlinger og gjennomsnittsalder på dem per behandlingstype. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsPneBehandlingerPerBehandlingstypeGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$Antall\u00C5pneOgTypeOgGjennomsnittsalder`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/\u00E5pne-behandlinger-per-behandlingstype-med-periode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antall åpne behandlinger og gjennomsnittsalder på dem per behandlingstype. */
        get: {
            parameters: {
                query: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsPneBehandlingerPerBehandlingstypeMedPeriodeGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                    /** @description For hvilke periode som skal gjøres oppslag på */
                    oppslagsPeriode: PathsPneBehandlingerPerBehandlingstypeMedPeriodeGetParametersQueryOppslagsPeriode;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$Antall\u00C5pneOgTypeOgGjennomsnittsalder`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandling-per-steggruppe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingPerSteggruppeGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                    /** @description For hvilke oppgavetyper. Tom liste betyr alle. */
                    oppgaveTyper?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingPerSteggruppe"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/fordeling-\u00E5pne-behandlinger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returnerer en liste over fordelingen på åpne behandlinger. Bøtte nr 1 teller antall
         *     behandlinger som er enhet * bøtteStørrelse gammel . Bøtte nr antallBøtter + 1 teller
         *     antall behandlinger eldre enn bøttestørrelsen.
         */
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange bøtter skal åpne behandlinger plasseres i? */
                    "antallB\u00F8tter"?: number;
                    /** @description Week, month, day, etc. */
                    enhet: PathsBehandlingerFordelingPneBehandlingerGetParametersQueryEnhet;
                    /** @description Hver bøtte er enhet * bøtteStørrelse stor. */
                    "b\u00F8tteSt\u00F8rrelse"?: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerFordelingPneBehandlingerGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.Fordeling\u00C5pneBehandlinger"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/fordeling-lukkede-behandlinger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returnerer en liste over behandlingstiden på lukkede behandlinger. Bøtte nr 1 teller antall
         *     behandlinger som er enhet * bøtteStørrelse gammel . Bøtte nr antallBøtter + 1 teller
         *     antall behandlinger eldre enn bøttestørrelsen.
         */
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange bøtter skal åpne behandlinger plasseres i? */
                    "antallB\u00F8tter"?: number;
                    /** @description Week, month, day, etc. */
                    enhet: PathsBehandlingerFordelingLukkedeBehandlingerGetParametersQueryEnhet;
                    /** @description Hver bøtte er enhet * bøtteStørrelse stor. */
                    "b\u00F8tteSt\u00F8rrelse"?: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerFordelingLukkedeBehandlingerGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.FordelingLukkedeBehandlinger"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgaver-per-steggruppe-med-periode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsOppgaverPerSteggruppeMedPeriodeGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                    /** @description For hvilke periode som skal gjøres oppslag på */
                    oppslagsPeriode: PathsOppgaverPerSteggruppeMedPeriodeGetParametersQueryOppslagsPeriode;
                    /** @description For hvilke oppgavetyper. Tom liste betyr alle. */
                    oppgaveTyper?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.OppgaverPerSteggruppe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/utvikling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description Hvor mange dager å lage fordeling på. */
                    antallDager: number;
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerUtviklingGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlinEndringerPerDag`"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/p\u00E5-vent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerPVentGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.Vente\u00E5rsakOgGjennomsnitt"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/p\u00E5-vent-med-periode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerPVentMedPeriodeGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                    /** @description For hvilke periode som skal gjøres oppslag på */
                    oppslagsPeriode: PathsBehandlingerPVentMedPeriodeGetParametersQueryOppslagsPeriode;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.Vente\u00E5rsakOgGjennomsnitt"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/\u00E5rsak-til-behandling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerRsakTilBehandlingGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingAarsakAntallGjennomsnitt"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandlinger/retur": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hvor mange saker som blir returnert fra kvalitetssikrer og beslutter og hvor lenge disse sakene har ligget etter retur. */
        get: {
            parameters: {
                query?: {
                    /** @description For hvilke behandlingstyper. Tom liste betyr alle. */
                    behandlingstyper?: PathsBehandlingerReturGetParametersQueryBehandlingstyper[];
                    /** @description For hvilke enheter. Tom liste betyr alle. */
                    enheter?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingAvklaringsbehovReturDTO"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon": {
            /** @enum {string} */
            kode: NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonKode;
            kreverToTrinn: boolean;
            kvalitetssikres: boolean;
            "l\u00F8sesAv": NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonLSesAv[];
            /** @enum {string} */
            "l\u00F8sesISteg": NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonLSesISteg;
            /** @enum {string} */
            type: NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonType;
            name: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto": {
            avklaringsbehovDefinisjon: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon"];
            endringer: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO"][];
            /** Format: int64 */
            id?: number | null;
            /** @enum {string} */
            status: NoNavAapBehandlingsflytKontraktHendelseAvklaringsbehovHendelseDtoStatus;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO": {
            begrunnelse?: string | null;
            endretAv: string;
            /**
             * Format: date
             * @example 2025-04-01
             */
            frist?: string | null;
            /** @enum {string} */
            status: NoNavAapBehandlingsflytKontraktHendelseEndringDTOStatus;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            tidsstempel: string;
            "\u00E5rsakTilRetur": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur"][];
            /** @enum {string|null} */
            "\u00E5rsakTilSattP\u00E5Vent"?: NoNavAapBehandlingsflytKontraktHendelseEndringDTORsakTilSattPVent;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur": {
            /** @enum {string} */
            "\u00E5rsak": NoNavAapBehandlingsflytKontraktHendelseRsakTilReturRsak;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.ArbeidIPeriode": {
            /**
             * Format: date
             * @example 2025-04-01
             */
            periodeFom: string;
            /**
             * Format: date
             * @example 2025-04-01
             */
            periodeTom: string;
            timerArbeidet: number;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.AvsluttetBehandlingDTO": {
            beregningsGrunnlag?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO"];
            diagnoser?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Diagnoser"];
            fritaksvurderinger?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Fritakvurdering"][] | null;
            perioderMedArbeidsopptrapping: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.PeriodeDTO"][];
            /** @enum {string|null} */
            resultat?: NoNavAapBehandlingsflytKontraktStatistikkAvsluttetBehandlingDTOResultat;
            rettighetstypePerioder: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.RettighetstypePeriode"][];
            tilkjentYtelse: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelseDTO"];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            vedtakstidspunkt?: string | null;
            "vilk\u00E5rsResultat": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsResultatDTO"];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO": {
            grunnlag11_19dto?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            "grunnlagUf\u00F8re"?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagUf\u00F8reDTO"];
            grunnlagYrkesskade?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagYrkesskadeDTO"];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Diagnoser": {
            bidiagnoser: string[];
            diagnosekode: string;
            kodeverk: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Fritakvurdering": {
            /**
             * Format: date
             * @example 2025-04-01
             */
            fraDato: string;
            harFritak: boolean;
            /**
             * Format: date
             * @example 2025-04-01
             */
            tilDato?: string | null;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO": {
            er6GBegrenset: boolean;
            erGjennomsnitt: boolean;
            /** Format: double */
            grunnlaget: number;
            /** @description Key type: kotlin.String */
            inntekter: {
                [key: string]: number;
            };
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagUf\u00F8reDTO": {
            grunnlag: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            grunnlagYtterligereNedsatt: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Grunnlag11_19DTO"];
            grunnlaget: number;
            /** @enum {string} */
            type: NoNavAapBehandlingsflytKontraktStatistikkGrunnlagUfReDTOType;
            /** @description Key type: kotlin.String */
            "uf\u00F8reInntekterFraForeg\u00E5ende\u00C5r": {
                [key: string]: number;
            };
            /** Format: int32 */
            "uf\u00F8reYtterligereNedsattArbeidsevne\u00C5r": number;
            /** Format: int32 */
            "uf\u00F8regrad": number;
            "uf\u00F8regrader": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Uf\u00F8re"][];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.GrunnlagYrkesskadeDTO": {
            andelSomIkkeSkyldesYrkesskade: number;
            andelSomSkyldesYrkesskade: number;
            /** Format: int32 */
            andelYrkesskade: number;
            "antatt\u00C5rligInntektYrkesskadeTidspunktet": number;
            /** Format: int32 */
            benyttetAndelForYrkesskade: number;
            beregningsgrunnlag: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.BeregningsgrunnlagDTO"];
            grunnlagEtterYrkesskadeFordel: number;
            grunnlagForBeregningAvYrkesskadeandel: number;
            grunnlaget: number;
            "inkludererUf\u00F8re": boolean;
            /** Format: int32 */
            terskelverdiForYrkesskade: number;
            /** Format: int32 */
            yrkesskadeTidspunkt: number;
            yrkesskadeinntektIG: number;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.MeldekortDTO": {
            arbeidIPeriode: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.ArbeidIPeriode"][];
            journalpostId: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.PeriodeDTO": {
            /**
             * Format: date
             * @example 2025-04-01
             */
            fom: string;
            /**
             * Format: date
             * @example 2025-04-01
             */
            tom: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.RettighetstypePeriode": {
            /**
             * Format: date
             * @example 2025-04-01
             */
            fraDato: string;
            /** @enum {string} */
            rettighetstype: NoNavAapBehandlingsflytKontraktStatistikkRettighetstypePeriodeRettighetstype;
            /**
             * Format: date
             * @example 2025-04-01
             */
            tilDato: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.StoppetBehandling": {
            avklaringsbehov: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto"][];
            avsluttetBehandling?: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.AvsluttetBehandlingDTO"];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            behandlingOpprettetTidspunkt: string;
            /** Format: uuid */
            behandlingReferanse: string;
            /** @enum {string} */
            behandlingStatus: NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingBehandlingStatus;
            /** @enum {string} */
            behandlingType: NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingBehandlingType;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            hendelsesTidspunkt: string;
            ident: string;
            identerForSak: string[];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            mottattTid: string;
            nyeMeldekort: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.MeldekortDTO"][];
            opprettetAv?: string | null;
            /** Format: uuid */
            relatertBehandling?: string | null;
            relatertFagsystem?: string | null;
            /** @enum {string} */
            sakStatus: NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingSakStatus;
            saksnummer: string;
            /** @enum {string} */
            soknadsFormat: NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingSoknadsFormat;
            "s\u00F8knadIder": components["schemas"]["no.nav.aap.verdityper.dokument.JournalpostId"][];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            tidspunktSisteEndring?: string | null;
            versjon: string;
            vurderingsbehov: NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingVurderingsbehov[];
            "\u00E5rsakTilOpprettelse": string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelseDTO": {
            perioder: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelsePeriodeDTO"][];
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.TilkjentYtelsePeriodeDTO": {
            /** Format: int32 */
            antallBarn: number;
            /** Format: double */
            barnetillegg: number;
            /** Format: double */
            barnetilleggSats: number;
            /** Format: double */
            dagsats: number;
            /**
             * Format: date
             * @example 2025-04-01
             */
            fraDato: string;
            /** Format: double */
            gradering: number;
            /** @enum {string} */
            minsteSats: NoNavAapBehandlingsflytKontraktStatistikkTilkjentYtelsePeriodeDTOMinsteSats;
            /** Format: double */
            redusertDagsats: number;
            /**
             * Format: date
             * @example 2025-04-01
             */
            tilDato: string;
            /**
             * Format: date
             * @example 2025-04-01
             */
            utbetalingsdato: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Uf\u00F8re": {
            /** Format: int32 */
            grad: number;
            /**
             * Format: date
             * @example 2025-04-01
             */
            virkningstidspunkt: string;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rDTO": {
            perioder: components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsPeriodeDTO"][];
            /** @enum {string} */
            "vilk\u00E5rType": NoNavAapBehandlingsflytKontraktStatistikkVilkRDTOVilkRType;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsPeriodeDTO": {
            "avslags\u00E5rsak"?: string | null;
            /**
             * Format: date
             * @example 2025-04-01
             */
            fraDato: string;
            "innvilgelses\u00E5rsak"?: string | null;
            manuellVurdering: boolean;
            /**
             * Format: date
             * @example 2025-04-01
             */
            tilDato: string;
            /** @enum {string} */
            utfall: NoNavAapBehandlingsflytKontraktStatistikkVilkRsPeriodeDTOUtfall;
        };
        "no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rsResultatDTO": {
            /** @enum {string} */
            typeBehandling: NoNavAapBehandlingsflytKontraktStatistikkVilkRsResultatDTOTypeBehandling;
            "vilk\u00E5r": components["schemas"]["no.nav.aap.behandlingsflyt.kontrakt.statistikk.Vilk\u00E5rDTO"][];
        };
        "no.nav.aap.oppgave.statistikk.OppgaveHendelse": {
            /** @enum {string} */
            hendelse: NoNavAapOppgaveStatistikkOppgaveHendelseHendelse;
            oppgaveTilStatistikkDto: components["schemas"]["no.nav.aap.oppgave.statistikk.OppgaveTilStatistikkDto"];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            sendtTidspunkt: string;
        };
        "no.nav.aap.oppgave.statistikk.OppgaveTilStatistikkDto": {
            avklaringsbehovKode: string;
            /** Format: uuid */
            behandlingRef?: string | null;
            /** @enum {string} */
            behandlingstype: NoNavAapOppgaveStatistikkOppgaveTilStatistikkDtoBehandlingstype;
            endretAv?: string | null;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            endretTidspunkt?: string | null;
            enhet: string;
            harHasteMarkering?: boolean | null;
            /** Format: int64 */
            id?: number | null;
            /** Format: int64 */
            journalpostId?: number | null;
            opprettetAv: string;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            opprettetTidspunkt: string;
            personIdent?: string | null;
            reservertAv?: string | null;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            reservertTidspunkt?: string | null;
            saksnummer?: string | null;
            /** @enum {string} */
            status: NoNavAapOppgaveStatistikkOppgaveTilStatistikkDtoStatus;
            /** Format: int64 */
            versjon: number;
        };
        "no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon": {
            /** @enum {string} */
            kode: NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonKode;
            kreverToTrinn: boolean;
            "l\u00F8sesAv": NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonLSesAv[];
            /** @enum {string} */
            "l\u00F8sesISteg": NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonLSesISteg;
            /** @enum {string} */
            type: NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonType;
            name: string;
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto": {
            avklaringsbehovDefinisjon: components["schemas"]["no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon"];
            endringer: components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO"][];
            /** @enum {string} */
            status: NoNavAapPostmottakKontraktHendelseAvklaringsbehovHendelseDtoStatus;
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse": {
            avklaringsbehov: components["schemas"]["no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto"][];
            /** @enum {string} */
            behandlingType: NoNavAapPostmottakKontraktHendelseDokumentflytStoppetHendelseBehandlingType;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            hendelsesTidspunkt: string;
            ident: string;
            journalpostId: components["schemas"]["no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId"];
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            opprettetTidspunkt: string;
            /** Format: uuid */
            referanse: string;
            saksnummer?: string | null;
            /** @enum {string} */
            status: NoNavAapPostmottakKontraktHendelseDokumentflytStoppetHendelseStatus;
        };
        "no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO": {
            begrunnelse?: string | null;
            endretAv: string;
            /**
             * Format: date
             * @example 2025-04-01
             */
            frist?: string | null;
            /** @enum {string} */
            status: NoNavAapPostmottakKontraktHendelseEndringDTOStatus;
            /**
             * Format: date-time
             * @example 2025-04-01T12:30:00
             */
            tidsstempel: string;
            /** @enum {string|null} */
            "\u00E5rsakTilSattP\u00E5Vent"?: NoNavAapPostmottakKontraktHendelseEndringDTORsakTilSattPVent;
        };
        /** Format: int64 */
        "no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId": number;
        "no.nav.aap.statistikk.api.BehandlingstidPerDagDTO": {
            /**
             * Format: date
             * @example 2025-04-01
             */
            dag: string;
            /** Format: double */
            snitt: number;
        };
        "no.nav.aap.statistikk.api.FordelingLukkedeBehandlinger": {
            /** Format: int32 */
            antall: number;
            /** Format: int32 */
            "b\u00F8tte": number;
        };
        "no.nav.aap.statistikk.api.Fordeling\u00C5pneBehandlinger": {
            /** Format: int32 */
            antall: number;
            /** Format: int32 */
            "b\u00F8tte": number;
        };
        "no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$Antall\u00C5pneOgTypeOgGjennomsnittsalder`": {
            /** Format: int32 */
            "antall\u00C5pne": number;
            /** @enum {string} */
            behandlingstype: NoNavAapStatistikkApiProduksjonsstyringApiKt$hentBehandlingstidPerDag$AntallPneOgTypeOgGjennomsnittsalderBehandlingstype;
            /** Format: double */
            gjennomsnittsalder: number;
        };
        "no.nav.aap.statistikk.api.`ProduksjonsstyringApiKt$hentBehandlingstidPerDag$BehandlinEndringerPerDag`": {
            /** Format: int32 */
            avsluttede: number;
            /**
             * Format: date
             * @example 2025-04-01
             */
            dato: string;
            /** Format: int32 */
            nye: number;
            /** Format: int32 */
            totalt: number;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingAarsakAntallGjennomsnitt": {
            /** Format: int32 */
            antall: number;
            /** Format: double */
            gjennomsnittligAlder: number;
            "\u00E5rsak": string;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingAvklaringsbehovRetur": {
            /** Format: int32 */
            "antall\u00C5pneBehandlinger": number;
            avklaringsbehov: string;
            /** Format: double */
            gjennomsnittTidFraRetur: number;
            returFra: string;
            "retur\u00C5rsak": string;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingAvklaringsbehovReturDTO": {
            returerPerAvklaringsbehov: components["schemas"]["no.nav.aap.statistikk.produksjonsstyring.BehandlingAvklaringsbehovRetur"][];
            /** Format: int32 */
            totalt: number;
        };
        "no.nav.aap.statistikk.produksjonsstyring.BehandlingPerSteggruppe": {
            /** Format: int32 */
            antall: number;
            steggruppe: string;
        };
        "no.nav.aap.statistikk.produksjonsstyring.OppgaverPerSteggruppe": {
            /** Format: int32 */
            lukkede: number;
            /** Format: int32 */
            nye: number;
            /** Format: int32 */
            totalt: number;
        };
        "no.nav.aap.statistikk.produksjonsstyring.Vente\u00E5rsakOgGjennomsnitt": {
            /** Format: int32 */
            antall: number;
            /** Format: double */
            gjennomsnittligAlder: number;
            "\u00E5rsak": string;
        };
        "no.nav.aap.verdityper.dokument.JournalpostId": {
            identifikator: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsBehandlingstidGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsPneBehandlingerPerBehandlingstypeGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsPneBehandlingerPerBehandlingstypeMedPeriodeGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsPneBehandlingerPerBehandlingstypeMedPeriodeGetParametersQueryOppslagsPeriode {
    DENNE_UKEN = "DENNE_UKEN",
    FORRIGE_UKE = "FORRIGE_UKE",
    IDAG = "IDAG",
    IG_R = "IG\u00C5R"
}
export enum PathsBehandlingPerSteggruppeGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerFordelingPneBehandlingerGetParametersQueryEnhet {
    DAG = "DAG",
    M_NED = "M\u00C5NED",
    UKE = "UKE",
    _R = "\u00C5R"
}
export enum PathsBehandlingerFordelingPneBehandlingerGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerFordelingLukkedeBehandlingerGetParametersQueryEnhet {
    DAG = "DAG",
    M_NED = "M\u00C5NED",
    UKE = "UKE",
    _R = "\u00C5R"
}
export enum PathsBehandlingerFordelingLukkedeBehandlingerGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsOppgaverPerSteggruppeMedPeriodeGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsOppgaverPerSteggruppeMedPeriodeGetParametersQueryOppslagsPeriode {
    DENNE_UKEN = "DENNE_UKEN",
    FORRIGE_UKE = "FORRIGE_UKE",
    IDAG = "IDAG",
    IG_R = "IG\u00C5R"
}
export enum PathsBehandlingerUtviklingGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerPVentGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerPVentMedPeriodeGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerPVentMedPeriodeGetParametersQueryOppslagsPeriode {
    DENNE_UKEN = "DENNE_UKEN",
    FORRIGE_UKE = "FORRIGE_UKE",
    IDAG = "IDAG",
    IG_R = "IG\u00C5R"
}
export enum PathsBehandlingerRsakTilBehandlingGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum PathsBehandlingerReturGetParametersQueryBehandlingstyper {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonKode {
    Value4101 = "4101",
    Value4102 = "4102",
    Value4201 = "4201",
    Value5001 = "5001",
    Value5002 = "5002",
    Value5003 = "5003",
    Value5004 = "5004",
    Value5005 = "5005",
    Value5006 = "5006",
    Value5007 = "5007",
    Value5008 = "5008",
    Value5009 = "5009",
    Value5010 = "5010",
    Value5011 = "5011",
    Value5012 = "5012",
    Value5013 = "5013",
    Value5014 = "5014",
    Value5015 = "5015",
    Value5016 = "5016",
    Value5017 = "5017",
    Value5018 = "5018",
    Value5019 = "5019",
    Value5020 = "5020",
    Value5021 = "5021",
    Value5022 = "5022",
    Value5023 = "5023",
    Value5024 = "5024",
    Value5025 = "5025",
    Value5026 = "5026",
    Value5027 = "5027",
    Value5028 = "5028",
    Value5029 = "5029",
    Value5030 = "5030",
    Value5031 = "5031",
    Value5032 = "5032",
    Value5033 = "5033",
    Value5034 = "5034",
    Value5035 = "5035",
    Value5040 = "5040",
    Value5050 = "5050",
    Value5051 = "5051",
    Value5052 = "5052",
    Value5053 = "5053",
    Value5056 = "5056",
    Value5057 = "5057",
    Value5096 = "5096",
    Value5097 = "5097",
    Value5098 = "5098",
    Value5099 = "5099",
    Value5999 = "5999",
    Value6000 = "6000",
    Value6001 = "6001",
    Value6002 = "6002",
    Value6003 = "6003",
    Value6004 = "6004",
    Value6005 = "6005",
    Value6006 = "6006",
    Value6007 = "6007",
    Value6008 = "6008",
    Value6009 = "6009",
    Value6010 = "6010",
    Value7001 = "7001",
    Value8001 = "8001",
    Value8002 = "8002",
    Value8003 = "8003",
    Value9001 = "9001",
    Value9002 = "9002",
    Value9003 = "9003",
    Value9004 = "9004"
}
export enum NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonLSesAv {
    BESLUTTER = "BESLUTTER",
    DRIFT = "DRIFT",
    KVALITETSSIKRER = "KVALITETSSIKRER",
    LES = "LES",
    PRODUKSJONSSTYRING = "PRODUKSJONSSTYRING",
    SAKSBEHANDLER_NASJONAL = "SAKSBEHANDLER_NASJONAL",
    SAKSBEHANDLER_OPPFOLGING = "SAKSBEHANDLER_OPPFOLGING"
}
export enum NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonLSesISteg {
    ARBEIDSOPPTRAPPING = "ARBEIDSOPPTRAPPING",
    AVBRYT_REVURDERING = "AVBRYT_REVURDERING",
    AVKLAR_OPPF_LGING = "AVKLAR_OPPF\u00D8LGING",
    AVKLAR_STUDENT = "AVKLAR_STUDENT",
    AVKLAR_SYKDOM = "AVKLAR_SYKDOM",
    BARNETILLEGG = "BARNETILLEGG",
    BEHANDLENDE_ENHET = "BEHANDLENDE_ENHET",
    BEREGN_TILKJENT_YTELSE = "BEREGN_TILKJENT_YTELSE",
    BREV = "BREV",
    DU_ER_ET_ANNET_STED = "DU_ER_ET_ANNET_STED",
    EFFEKTUER_11_7 = "EFFEKTUER_11_7",
    FASTSETT_ARBEIDSEVNE = "FASTSETT_ARBEIDSEVNE",
    FASTSETT_BEREGNINGSTIDSPUNKT = "FASTSETT_BEREGNINGSTIDSPUNKT",
    FASTSETT_GRUNNLAG = "FASTSETT_GRUNNLAG",
    FASTSETT_MELDEPERIODER = "FASTSETT_MELDEPERIODER",
    FASTSETT_RETTIGHETSTYPE = "FASTSETT_RETTIGHETSTYPE",
    FASTSETT_SYKDOMSVILK_RET = "FASTSETT_SYKDOMSVILK\u00C5RET",
    FASTSETT_UTTAK = "FASTSETT_UTTAK",
    FASTSETT_VEDTAKSLENGDE = "FASTSETT_VEDTAKSLENGDE",
    FATTE_VEDTAK = "FATTE_VEDTAK",
    FORESL__VEDTAK = "FORESL\u00C5_VEDTAK",
    FORMKRAV = "FORMKRAV",
    FRITAK_MELDEPLIKT = "FRITAK_MELDEPLIKT",
    FULLMEKTIG = "FULLMEKTIG",
    IKKE_OPPFYLT_MELDEPLIKT = "IKKE_OPPFYLT_MELDEPLIKT",
    IVERKSETT_BRUDD = "IVERKSETT_BRUDD",
    IVERKSETT_KONSEKVENS = "IVERKSETT_KONSEKVENS",
    IVERKSETT_VEDTAK = "IVERKSETT_VEDTAK",
    KLAGEBEHANDLING_KONTOR = "KLAGEBEHANDLING_KONTOR",
    KLAGEBEHANDLING_NAY = "KLAGEBEHANDLING_NAY",
    KLAGEBEHANDLING_OPPSUMMERING = "KLAGEBEHANDLING_OPPSUMMERING",
    KVALITETSSIKRING = "KVALITETSSIKRING",
    MANGLENDE_LIGNING = "MANGLENDE_LIGNING",
    OMGJ_RING = "OMGJ\u00D8RING",
    OPPRETTHOLDELSE = "OPPRETTHOLDELSE",
    OPPRETT_REVURDERING = "OPPRETT_REVURDERING",
    OVERGANG_ARBEID = "OVERGANG_ARBEID",
    OVERGANG_UFORE = "OVERGANG_UFORE",
    P_KLAGET_BEHANDLING = "P\u00C5KLAGET_BEHANDLING",
    REFUSJON_KRAV = "REFUSJON_KRAV",
    SAMORDNING_ANDRE_STATLIGE_YTELSER = "SAMORDNING_ANDRE_STATLIGE_YTELSER",
    SAMORDNING_ARBEIDSGIVER = "SAMORDNING_ARBEIDSGIVER",
    SAMORDNING_AVSLAG = "SAMORDNING_AVSLAG",
    SAMORDNING_GRADERING = "SAMORDNING_GRADERING",
    SAMORDNING_SYKESTIPEND = "SAMORDNING_SYKESTIPEND",
    SAMORDNING_TJENESTEPENSJON_REFUSJONSKRAV = "SAMORDNING_TJENESTEPENSJON_REFUSJONSKRAV",
    SAMORDNING_UF_RE = "SAMORDNING_UF\u00D8RE",
    SEND_FORVALTNINGSMELDING = "SEND_FORVALTNINGSMELDING",
    SIMULERING = "SIMULERING",
    START_BEHANDLING = "START_BEHANDLING",
    START_OPPF_LGINGSBEHANDLING = "START_OPPF\u00D8LGINGSBEHANDLING",
    SVAR_FRA_ANDREINSTANS = "SVAR_FRA_ANDREINSTANS",
    SYKDOMSVURDERING_BREV = "SYKDOMSVURDERING_BREV",
    S_KNAD = "S\u00D8KNAD",
    TREKK_KLAGE = "TREKK_KLAGE",
    UDEFINERT = "UDEFINERT",
    VIS_GRUNNLAG = "VIS_GRUNNLAG",
    VURDER_AKTIVITETSPLIKT_11_7 = "VURDER_AKTIVITETSPLIKT_11_7",
    VURDER_AKTIVITETSPLIKT_11_9 = "VURDER_AKTIVITETSPLIKT_11_9",
    VURDER_ALDER = "VURDER_ALDER",
    VURDER_BISTANDSBEHOV = "VURDER_BISTANDSBEHOV",
    VURDER_INNTEKTSBORTFALL = "VURDER_INNTEKTSBORTFALL",
    VURDER_LOVVALG = "VURDER_LOVVALG",
    VURDER_MEDLEMSKAP = "VURDER_MEDLEMSKAP",
    VURDER_OPPHOLDSKRAV = "VURDER_OPPHOLDSKRAV",
    VURDER_RETTIGHETSPERIODE = "VURDER_RETTIGHETSPERIODE",
    VURDER_SYKEPENGEERSTATNING = "VURDER_SYKEPENGEERSTATNING",
    VURDER_YRKESSKADE = "VURDER_YRKESSKADE"
}
export enum NoNavAapBehandlingsflytKontraktAvklaringsbehovDefinisjonType {
    BREV = "BREV",
    BREV_VENTEPUNKT = "BREV_VENTEPUNKT",
    MANUELT_FRIVILLIG = "MANUELT_FRIVILLIG",
    MANUELT_P_KREVD = "MANUELT_P\u00C5KREVD",
    OVERSTYR = "OVERSTYR",
    VENTEPUNKT = "VENTEPUNKT"
}
export enum NoNavAapBehandlingsflytKontraktHendelseAvklaringsbehovHendelseDtoStatus {
    AVBRUTT = "AVBRUTT",
    AVSLUTTET = "AVSLUTTET",
    KVALITETSSIKRET = "KVALITETSSIKRET",
    OPPRETTET = "OPPRETTET",
    SENDT_TILBAKE_FRA_BESLUTTER = "SENDT_TILBAKE_FRA_BESLUTTER",
    SENDT_TILBAKE_FRA_KVALITETSSIKRER = "SENDT_TILBAKE_FRA_KVALITETSSIKRER",
    TOTRINNS_VURDERT = "TOTRINNS_VURDERT"
}
export enum NoNavAapBehandlingsflytKontraktHendelseEndringDTOStatus {
    AVBRUTT = "AVBRUTT",
    AVSLUTTET = "AVSLUTTET",
    KVALITETSSIKRET = "KVALITETSSIKRET",
    OPPRETTET = "OPPRETTET",
    SENDT_TILBAKE_FRA_BESLUTTER = "SENDT_TILBAKE_FRA_BESLUTTER",
    SENDT_TILBAKE_FRA_KVALITETSSIKRER = "SENDT_TILBAKE_FRA_KVALITETSSIKRER",
    TOTRINNS_VURDERT = "TOTRINNS_VURDERT"
}
export enum NoNavAapBehandlingsflytKontraktHendelseEndringDTORsakTilSattPVent {
    VENTER_P__FUNKSJONALITET = "VENTER_P\u00C5_FUNKSJONALITET",
    VENTER_P__FUNKSJONALITET_AVSLAG_11_27 = "VENTER_P\u00C5_FUNKSJONALITET_AVSLAG_11_27",
    VENTER_P__KLAGE_IMPLEMENTASJON = "VENTER_P\u00C5_KLAGE_IMPLEMENTASJON",
    VENTER_P__MASKINELL_AVKLARING = "VENTER_P\u00C5_MASKINELL_AVKLARING",
    VENTER_P__MEDISINSKE_OPPLYSNINGER = "VENTER_P\u00C5_MEDISINSKE_OPPLYSNINGER",
    VENTER_P__OPPLYSNINGER = "VENTER_P\u00C5_OPPLYSNINGER",
    VENTER_P__OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER = "VENTER_P\u00C5_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER",
    VENTER_P__SVAR_FRA_BRUKER = "VENTER_P\u00C5_SVAR_FRA_BRUKER",
    VENTER_P__SVAR_P__FORH_NDSVARSEL = "VENTER_P\u00C5_SVAR_P\u00C5_FORH\u00C5NDSVARSEL",
    VENTER_P__UTENLANDSK_VIDEREFORING_AVKLARING = "VENTER_P\u00C5_UTENLANDSK_VIDEREFORING_AVKLARING",
    VENTER_P__VURDERING_AV_ROL = "VENTER_P\u00C5_VURDERING_AV_ROL"
}
export enum NoNavAapBehandlingsflytKontraktHendelseRsakTilReturRsak {
    ANNET = "ANNET",
    FEIL_LOVANVENDELSE = "FEIL_LOVANVENDELSE",
    FOR_DETALJERT = "FOR_DETALJERT",
    IKKE_INDIVIDUELL_OG_KONKRET = "IKKE_INDIVIDUELL_OG_KONKRET",
    MANGELFULL_BEGRUNNELSE = "MANGELFULL_BEGRUNNELSE",
    MANGLENDE_UTREDNING = "MANGLENDE_UTREDNING",
    SKRIVEFEIL = "SKRIVEFEIL"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkAvsluttetBehandlingDTOResultat {
    AVBRUTT = "AVBRUTT",
    AVSLAG = "AVSLAG",
    INNVILGET = "INNVILGET",
    KLAGE_AVSL_TT = "KLAGE_AVSL\u00C5TT",
    KLAGE_DELVIS_OMGJ_RES = "KLAGE_DELVIS_OMGJ\u00D8RES",
    KLAGE_OMGJ_RES = "KLAGE_OMGJ\u00D8RES",
    KLAGE_OPPRETTHOLDES = "KLAGE_OPPRETTHOLDES",
    KLAGE_TRUKKET = "KLAGE_TRUKKET",
    TRUKKET = "TRUKKET"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkGrunnlagUfReDTOType {
    STANDARD = "STANDARD",
    YTTERLIGERE_NEDSATT = "YTTERLIGERE_NEDSATT"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkRettighetstypePeriodeRettighetstype {
    ARBEIDSS_KER = "ARBEIDSS\u00D8KER",
    BISTANDSBEHOV = "BISTANDSBEHOV",
    STUDENT = "STUDENT",
    SYKEPENGEERSTATNING = "SYKEPENGEERSTATNING",
    VURDERES_FOR_UF_RETRYGD = "VURDERES_FOR_UF\u00D8RETRYGD"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingBehandlingStatus {
    AVSLUTTET = "AVSLUTTET",
    IVERKSETTES = "IVERKSETTES",
    OPPRETTET = "OPPRETTET",
    UTREDES = "UTREDES"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingBehandlingType {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Klage = "Klage",
    Oppf_lgingsBehandling = "Oppf\u00F8lgingsBehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingSakStatus {
    AVSLUTTET = "AVSLUTTET",
    L_PENDE = "L\u00D8PENDE",
    OPPRETTET = "OPPRETTET",
    UTREDES = "UTREDES"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingSoknadsFormat {
    DIGITAL = "DIGITAL",
    PAPIR = "PAPIR"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkStoppetBehandlingVurderingsbehov {
    AKTIVITETSMELDING = "AKTIVITETSMELDING",
    AKTIVITETSPLIKT_11_7 = "AKTIVITETSPLIKT_11_7",
    AKTIVITETSPLIKT_11_9 = "AKTIVITETSPLIKT_11_9",
    AVVIST_LEGEERKL_RING = "AVVIST_LEGEERKL\u00C6RING",
    BARNETILLEGG = "BARNETILLEGG",
    BARNETILLEGG_SATS_REGULERING = "BARNETILLEGG_SATS_REGULERING",
    DIALOGMELDING = "DIALOGMELDING",
    D_DSFALL_BARN = "D\u00D8DSFALL_BARN",
    D_DSFALL_BRUKER = "D\u00D8DSFALL_BRUKER",
    EFFEKTUER_AKTIVITETSPLIKT = "EFFEKTUER_AKTIVITETSPLIKT",
    EFFEKTUER_AKTIVITETSPLIKT_11_9 = "EFFEKTUER_AKTIVITETSPLIKT_11_9",
    FORUTGAENDE_MEDLEMSKAP = "FORUTGAENDE_MEDLEMSKAP",
    FRITAK_MELDEPLIKT = "FRITAK_MELDEPLIKT",
    G_REGULERING = "G_REGULERING",
    HELHETLIG_VURDERING = "HELHETLIG_VURDERING",
    INSTITUSJONSOPPHOLD = "INSTITUSJONSOPPHOLD",
    KLAGE = "KLAGE",
    KLAGE_TRUKKET = "KLAGE_TRUKKET",
    LEGEERKL_RING = "LEGEERKL\u00C6RING",
    LOVVALG_OG_MEDLEMSKAP = "LOVVALG_OG_MEDLEMSKAP",
    MELDEKORT = "MELDEKORT",
    MIGRER_RETTIGHETSPERIODE = "MIGRER_RETTIGHETSPERIODE",
    MOTTATT_KABAL_HENDELSE = "MOTTATT_KABAL_HENDELSE",
    OPPF_LGINGSOPPGAVE = "OPPF\u00D8LGINGSOPPGAVE",
    OPPHOLDSKRAV = "OPPHOLDSKRAV",
    OVERGANG_ARBEID = "OVERGANG_ARBEID",
    OVERGANG_UFORE = "OVERGANG_UFORE",
    REFUSJONSKRAV = "REFUSJONSKRAV",
    REVURDERING_AVBRUTT = "REVURDERING_AVBRUTT",
    REVURDER_BEREGNING = "REVURDER_BEREGNING",
    REVURDER_LOVVALG = "REVURDER_LOVVALG",
    REVURDER_MANUELL_INNTEKT = "REVURDER_MANUELL_INNTEKT",
    REVURDER_MEDLEMSKAP = "REVURDER_MEDLEMSKAP",
    REVURDER_MELDEPLIKT_RIMELIG_GRUNN = "REVURDER_MELDEPLIKT_RIMELIG_GRUNN",
    REVURDER_SAMORDNING = "REVURDER_SAMORDNING",
    REVURDER_SAMORDNING_ANDRE_FOLKETRYGDYTELSER = "REVURDER_SAMORDNING_ANDRE_FOLKETRYGDYTELSER",
    REVURDER_SAMORDNING_ANDRE_STATLIGE_YTELSER = "REVURDER_SAMORDNING_ANDRE_STATLIGE_YTELSER",
    REVURDER_SAMORDNING_ARBEIDSGIVER = "REVURDER_SAMORDNING_ARBEIDSGIVER",
    REVURDER_SAMORDNING_TJENESTEPENSJON = "REVURDER_SAMORDNING_TJENESTEPENSJON",
    REVURDER_SAMORDNING_UF_RE = "REVURDER_SAMORDNING_UF\u00D8RE",
    REVURDER_STUDENT = "REVURDER_STUDENT",
    REVURDER_SYKEPENGEERSTATNING = "REVURDER_SYKEPENGEERSTATNING",
    REVURDER_SYKESTIPEND = "REVURDER_SYKESTIPEND",
    REVURDER_YRKESSKADE = "REVURDER_YRKESSKADE",
    SAMORDNING_OG_AVREGNING = "SAMORDNING_OG_AVREGNING",
    SYKDOM_ARBEVNE_BEHOV_FOR_BISTAND = "SYKDOM_ARBEVNE_BEHOV_FOR_BISTAND",
    S_KNAD = "S\u00D8KNAD",
    S_KNAD_TRUKKET = "S\u00D8KNAD_TRUKKET",
    UTENLANDSOPPHOLD_FOR_SOKNADSTIDSPUNKT = "UTENLANDSOPPHOLD_FOR_SOKNADSTIDSPUNKT",
    UTVID_VEDTAKSLENGDE = "UTVID_VEDTAKSLENGDE",
    VURDER_RETTIGHETSPERIODE = "VURDER_RETTIGHETSPERIODE"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkTilkjentYtelsePeriodeDTOMinsteSats {
    IKKE_MINSTESATS = "IKKE_MINSTESATS",
    MINSTESATS_OVER_25 = "MINSTESATS_OVER_25",
    MINSTESATS_UNDER_25 = "MINSTESATS_UNDER_25"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkVilkRDTOVilkRType {
    AKTIVITETSPLIKT = "AKTIVITETSPLIKT",
    ALDERSVILK_RET = "ALDERSVILK\u00C5RET",
    BISTANDSVILK_RET = "BISTANDSVILK\u00C5RET",
    GRUNNLAGET = "GRUNNLAGET",
    INNTEKTSBORTFALL = "INNTEKTSBORTFALL",
    LOVVALG = "LOVVALG",
    MEDLEMSKAP = "MEDLEMSKAP",
    OPPHOLDSKRAV = "OPPHOLDSKRAV",
    ORDIN_R_KVOTE = "ORDIN\u00C6R_KVOTE",
    OVERGANGARBEIDVILK_RET = "OVERGANGARBEIDVILK\u00C5RET",
    OVERGANGUF_REVILK_RET = "OVERGANGUF\u00D8REVILK\u00C5RET",
    SAMORDNING = "SAMORDNING",
    SAMORDNING_ANNEN_LOVGIVNING = "SAMORDNING_ANNEN_LOVGIVNING",
    STRAFFEGJENNOMF_RING = "STRAFFEGJENNOMF\u00D8RING",
    STUDENT = "STUDENT",
    SYKDOMSVILK_RET = "SYKDOMSVILK\u00C5RET",
    SYKEPENGEERSTATNING = "SYKEPENGEERSTATNING",
    SYKEPENGEERSTATNING_KVOTE = "SYKEPENGEERSTATNING_KVOTE"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkVilkRsPeriodeDTOUtfall {
    IKKE_OPPFYLT = "IKKE_OPPFYLT",
    IKKE_RELEVANT = "IKKE_RELEVANT",
    IKKE_VURDERT = "IKKE_VURDERT",
    OPPFYLT = "OPPFYLT"
}
export enum NoNavAapBehandlingsflytKontraktStatistikkVilkRsResultatDTOTypeBehandling {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Klage = "Klage",
    Oppf_lgingsBehandling = "Oppf\u00F8lgingsBehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export enum NoNavAapOppgaveStatistikkOppgaveHendelseHendelse {
    AVRESERVERT = "AVRESERVERT",
    LUKKET = "LUKKET",
    OPPDATERT = "OPPDATERT",
    OPPRETTET = "OPPRETTET",
    RESERVERT = "RESERVERT"
}
export enum NoNavAapOppgaveStatistikkOppgaveTilStatistikkDtoBehandlingstype {
    AKTIVITETSPLIKT = "AKTIVITETSPLIKT",
    AKTIVITETSPLIKT_11_9 = "AKTIVITETSPLIKT_11_9",
    DOKUMENT_H_NDTERING = "DOKUMENT_H\u00C5NDTERING",
    F_RSTEGANGSBEHANDLING = "F\u00D8RSTEGANGSBEHANDLING",
    JOURNALF_RING = "JOURNALF\u00D8RING",
    KLAGE = "KLAGE",
    OPPF_LGINGSBEHANDLING = "OPPF\u00D8LGINGSBEHANDLING",
    REVURDERING = "REVURDERING",
    SVAR_FRA_ANDREINSTANS = "SVAR_FRA_ANDREINSTANS",
    TILBAKEKREVING = "TILBAKEKREVING"
}
export enum NoNavAapOppgaveStatistikkOppgaveTilStatistikkDtoStatus {
    AVSLUTTET = "AVSLUTTET",
    OPPRETTET = "OPPRETTET"
}
export enum NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonKode {
    Value1337 = "1337",
    Value1338 = "1338",
    Value1339 = "1339",
    Value1340 = "1340",
    Value1341 = "1341",
    Value1342 = "1342",
    Value9001 = "9001"
}
export enum NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonLSesAv {
    BESLUTTER = "BESLUTTER",
    DRIFT = "DRIFT",
    KVALITETSSIKRER = "KVALITETSSIKRER",
    LES = "LES",
    PRODUKSJONSSTYRING = "PRODUKSJONSSTYRING",
    SAKSBEHANDLER_NASJONAL = "SAKSBEHANDLER_NASJONAL",
    SAKSBEHANDLER_OPPFOLGING = "SAKSBEHANDLER_OPPFOLGING"
}
export enum NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonLSesISteg {
    AVKLAR_SAK = "AVKLAR_SAK",
    AVKLAR_TEMA = "AVKLAR_TEMA",
    DIGITALISER_DOKUMENT = "DIGITALISER_DOKUMENT",
    ENDELIG_JOURNALF_RING = "ENDELIG_JOURNALF\u00D8RING",
    IVERKSETTES = "IVERKSETTES",
    OVERLEVER_TIL_FAGSYSTEM = "OVERLEVER_TIL_FAGSYSTEM",
    SETT_FAGSAK = "SETT_FAGSAK",
    START_BEHANDLING = "START_BEHANDLING",
    UDEFINERT = "UDEFINERT",
    VIDERESEND = "VIDERESEND"
}
export enum NoNavAapPostmottakKontraktAvklaringsbehovDefinisjonType {
    MANUELT_FRIVILLIG = "MANUELT_FRIVILLIG",
    MANUELT_P_KREVD = "MANUELT_P\u00C5KREVD",
    VENTEPUNKT = "VENTEPUNKT"
}
export enum NoNavAapPostmottakKontraktHendelseAvklaringsbehovHendelseDtoStatus {
    AVBRUTT = "AVBRUTT",
    AVSLUTTET = "AVSLUTTET",
    OPPRETTET = "OPPRETTET",
    SENDT_TILBAKE_FRA_BESLUTTER = "SENDT_TILBAKE_FRA_BESLUTTER"
}
export enum NoNavAapPostmottakKontraktHendelseDokumentflytStoppetHendelseBehandlingType {
    DokumentH_ndtering = "DokumentH\u00E5ndtering",
    Journalf_ring = "Journalf\u00F8ring"
}
export enum NoNavAapPostmottakKontraktHendelseDokumentflytStoppetHendelseStatus {
    AVSLUTTET = "AVSLUTTET",
    IVERKSETTES = "IVERKSETTES",
    OPPRETTET = "OPPRETTET",
    UTREDES = "UTREDES"
}
export enum NoNavAapPostmottakKontraktHendelseEndringDTOStatus {
    AVBRUTT = "AVBRUTT",
    AVSLUTTET = "AVSLUTTET",
    OPPRETTET = "OPPRETTET",
    SENDT_TILBAKE_FRA_BESLUTTER = "SENDT_TILBAKE_FRA_BESLUTTER"
}
export enum NoNavAapPostmottakKontraktHendelseEndringDTORsakTilSattPVent {
    VENTER_P__BEHANDLING_I_GOSYS = "VENTER_P\u00C5_BEHANDLING_I_GOSYS",
    VENTER_P__MEDISINSKE_OPPLYSNINGER = "VENTER_P\u00C5_MEDISINSKE_OPPLYSNINGER",
    VENTER_P__OPPLYSNINGER = "VENTER_P\u00C5_OPPLYSNINGER",
    VENTER_P__OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER = "VENTER_P\u00C5_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER",
    VENTER_P__SVAR_FRA_BRUKER = "VENTER_P\u00C5_SVAR_FRA_BRUKER",
    VENTER_P__VURDERING_AV_ROL = "VENTER_P\u00C5_VURDERING_AV_ROL"
}
export enum NoNavAapStatistikkApiProduksjonsstyringApiKt$hentBehandlingstidPerDag$AntallPneOgTypeOgGjennomsnittsalderBehandlingstype {
    Aktivitetsplikt = "Aktivitetsplikt",
    Aktivitetsplikt11_9 = "Aktivitetsplikt11_9",
    Dokumenth_ndtering = "Dokumenth\u00E5ndtering",
    F_rstegangsbehandling = "F\u00F8rstegangsbehandling",
    Journalf_ring = "Journalf\u00F8ring",
    Klage = "Klage",
    Oppf_lgingsbehandling = "Oppf\u00F8lgingsbehandling",
    Revurdering = "Revurdering",
    SvarFraAndreinstans = "SvarFraAndreinstans",
    Tilbakekreving = "Tilbakekreving"
}
export type operations = Record<string, never>;
