name: Merge Dependabot pull requester
on:
  workflow_dispatch:
  pull_request:

jobs:
  merge-pullrequests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pulls = await github.paginate(github.rest.pulls.list, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
            })
            
            const filtrert = pulls
                .filter((it) => {
                  return it.state == 'open';
                })
                .filter((it) => {
                  return !it.head.repo.fork;
                 })
                .filter((it) => {
                  return it.user.login === 'github-actions[bot]';
                })
                .map((it) => {
                    return {
                        title: it.title,
                        number: it.number,

                    }
                })
                .map(async (it) => {
                    const QUERY = `query($owner: String!, $repo: String!, $pull_number: Int!) {
                                          repository(owner: $owner, name:$repo) {
                                            pullRequest(number:$pull_number) {
                                              commits(last: 1) {
                                                nodes {
                                                  commit {
                                                    statusCheckRollup {
                                                      state
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }`

                    const result = await github.graphql(QUERY, {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number,
                    })
                    const [{ commit: lastCommit }] =
                        result.repository.pullRequest.commits.nodes

                    return {
                        title: it.title,
                        number: it.number,
                        checksOk: lastCommit.statusCheckRollup?.state === 'SUCCESS',
                    }
                })
            
            console.log("filtrert: " + filtrert.length)

            const allePrs = await Promise.all(filtrert)
            const mergeablePromise = allePrs
                .filter((it) => it.checksOk)
                .map(async (it) => {
                    const prdata = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number
                    })
                    return {
                        title: it.title,
                        number: it.number,
                        mergeable: prdata.data.mergeable
                    }
                })


            const mergeable = (await Promise.all(mergeablePromise))
                .filter((it) => {
                  return it.mergeable;
                })
            console.log("mergeable: " + mergeable.length)
            
            if (mergeable.length > 0) {
                const pr = mergeable[0]
                console.log('Merger PR', pr.title)
                await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge', {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    merge_method: 'squash'
                })
            
              console.log('Starter main workflow')
            
              await github.request(
                  'POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
                  {
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      workflow_id: bygg-og-publish.yml,
                      ref: 'main',
                  }
              )
            } else {
                console.log('Ingen PRer å merge')
            }
