name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      SKIP_YARN_COREPACK_CHECK: true
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generer schemas (uten enums)
        run: |
          for pkg in aap-behandlingsflyt aap-brev aap-postmottak-backend; do
            yarn openapi-typescript ./packages/${pkg}-typescript-types/openapi.json \
              -o ./packages/${pkg}-typescript-types/schema.d.ts
          done
      - name: Generer schemas (med enums)
        run: |
          for pkg in aap-oppgave aap-statistikk; do
            yarn openapi-typescript ./packages/${pkg}-typescript-types/openapi.json \
              -o ./packages/${pkg}-typescript-types/schema.ts --enum
          done
      - name: Bygg
        run: yarn run build
